apiVersion: batch/v1
kind: Job
metadata:
  name: osm2pgsql
  namespace: default
spec:
  template:
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: osm2pgsql
            optional: false
        image: 127.0.0.1:34060/osm-data:${CICD_EXECUTION_SEQUENCE}
        imagePullPolicy: Always
        name: osm2pgsql
      imagePullSecrets:
      - name: pipeline-docker-registry
      restartPolicy: Never
      schedulerName: default-scheduler
  backoffLimit: 1
